version: "3.8"

services:
  apache:
    build: ./docker/apache
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/workspace

  postgres:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:7-bullseye
