version: "3.8"

services:
  judger:
    build:
      context: .
      dockerfile: ./docker/judger/Dockerfile
      target: "development"
    depends_on:
      - postgres
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - coj-data:/data

  apache:
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
      target: "development"
    depends_on:
      - postgres
      - redis
    volumes:
      - coj-data:/data

  postgres:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

  redis:
    image: redis:7-bullseye

volumes:
  postgres-data:
  coj-data:
