version: "3.7"

networks:
  cuddly-chainsaw.network:
    driver: bridge

services:
  apache:
    image: php:8-apache
    restart: always
    container_name: cuddly-chainsaw.apache
    networks:
      - cuddly-chainsaw.network
    depends_on:
      - postgres
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/var/www/html

  postgres:
    image: postgres:14-alpine
    container_name: cuddly-chainsaw.postgres
    restart: always
    tty: true
    networks:
      - cuddly-chainsaw.network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:7-alpine
    restart: always
    tty: true
    container_name: cuddly-chainsaw.redis
    networks:
      - cuddly-chainsaw.network
