version: "3.8"

networks:
  net:
    driver: bridge

services:
  apache:
    networks:
      - net
    ports:
      - 80:80
    environment:
      - ENV=production

  postgres:
    networks:
      - net

  redis:
    networks:
      - net
