version: "3.8"

services:
  judger:
    network_mode: service:postgres

  apache:
    build:
      target: "development"
    network_mode: service:postgres

  redis:
    network_mode: service:postgres
